config/routes.rb
Rails.application.routes.draw do

  get 'login' => 'sessions#new', as: 'login'
  delete 'logout' => 'sessions#destroy', as: 'logout'

  get 'admin_menu' => 'welcome#admin_menu'
  get 'late_entries' => 'entries#late_entries'  
  get 'employees_absences' => 'entries#employees_absences'
  
  get 'employee_menu' => 'welcome#employee_menu'
  post 'working_hours' => 'entries#working_hours'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:edit]

  root 'welcome#index'
end

app/models/entry.rb
class Entry < ActiveRecord::Base

  def self.late_entries(tolerance, initial_date, final_date)
    late_entries = Entry.where("to_char(arrival_at, 'HH:MI') > ? AND
                 arrival_at BETWEEN ? AND ? ",
                 tolerance, initial_date, final_date)
    late_entries.group_by { |e| e.barcode }.sort
  end

  def self.current_period_entries(initial_date, final_date)
    Entry.where("cast(arrival_at as date) BETWEEN ? AND ?",
                initial_date.strftime("%Y-%m-%d"),
                final_date.strftime("%Y-%m-%d"))
  end

  def self.extract_employees_list(entries)
    entries.find_by_sql("SELECT DISTINCT barcode FROM entries;")
  end

  def self.get_period_working_days(initial_date, final_date)
    working_days = []
    
    (initial_date.day.to_i..final_date.day.to_i).to_a.each_with_index do |d, i|
      working_days << initial_date + i.day unless (initial_date + i.day).saturday? ||
                                                  (initial_date + i.day).sunday?
    end
    working_days
  end

  def self.get_absences(employees_list, working_days, entries)
    absences_counter = []
    absences = {}
    employees_list.each do |emp|
      working_days.each.with_index do |d, i|
        absences_counter << d.strftime("%Y-%m-%d") unless entries.detect do |entry|
          entry.barcode == emp.barcode &&
            entry.arrival_at.strftime("%Y-%m-%d") == d.strftime("%Y-%m-%d")
        end
      end
      absences[emp] = absences_counter
      absences_counter = []
    end
    absences
  end

end

app/models/period.rb
class Period < ActiveRecord::Base
  def self.current_period
    Period.all.detect { |p| Date.today >= p.initial_date && Date.today <= p.final_date }
  end

  def days_to_payday(payday)
    payday = Time.parse(payday.strftime("%Y-%m-%d"))
    today = Time.parse(Time.now.strftime("%Y-%m-%d"))
    
    total_minutes = (payday - today)/60
    hours = (total_minutes / 60).floor
    hours/24 
  end
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true,
            format: /\A\S+@\S+\z/,
            uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 10, allow_blank: true }

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types(:success, :info, :warning, :danger)

  private

  def require_signin
    unless current_user
      redirect_to new_session_url, warning: "Please sign in first!"
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :require_signin, except: :working_hours

  def late_entries
    @current_period = Period.current_period
    @initial_date = @current_period.initial_date
    @final_date = @current_period.final_date

    @arrival_tolerance = Schedule.first.arrival_tolerance.strftime("%H:%M")
    @late_entries = Entry.late_entries(@arrival_tolerance, @initial_date, @final_date) 
  end

  def employees_absences
    @current_period = Period.current_period
    @initial_date = @current_period.initial_date
    @final_date = @current_period.final_date

    entries = Entry.current_period_entries(@initial_date, @final_date)
    days = Entry.get_period_working_days(@initial_date, @final_date)
    employees = Entry.extract_employees_list(entries)
    @absences = Entry.get_absences(employees, days, entries)
  end

  def working_hours
    @current_period = Period.current_period

    if  @current_period.days_to_payday(@current_period.payday) == 3
      @initial_date = @current_period.initial_date
      @final_date = @current_period.final_date
      @barcode = params[:barcode]

      entries = Entry.current_period_entries(@initial_date, @final_date)

      @employee_entries = entries.where("barcode = ?", params[:barcode] )

    else
      redirect_to employee_menu_url, warning: "This report is available only 3 days
                                          before the paycheck day. Please check
                                          again the #{@current_period.payday - 3.days}"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # Login Page
  end
  
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:info] = "Welcome, #{user.name}!"
      redirect_to admin_menu_path
    else
      flash.now[:danger] = "Invalid email/password combination!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, info: "You're now signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :require_signin, only: :admin_menu 

  def index
  end

  def admin_menu
  end

  def employee_menu
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/entries_helper.rb
module EntriesHelper

  def calculate_hours(arrival, departure)
    arrival = Time.parse(arrival.strftime("%H:%M"))
    departure = Time.parse(departure.strftime("%H:%M"))
    
    total_minutes = (departure - arrival)/60

    hours = (total_minutes / 60).floor
    minutes = total_minutes.to_i % 60

    "#{hours} hour(s) #{minutes} minute(s)"
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

end

app/views/entries/employees_absences.html.erb
<h1>Employees with absences</h1>
<div class="well">
    <p>Current period: <%= @current_period.description %></p>
    <p>from <%= @current_period.initial_date %> to <%= @current_period.final_date %>.</p>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Employee barcode</th>
            <th>Total Absences<br> in the period</th>
            <th>Absences dates <br>(Weekends not included)</th>
        </tr>
    </thead>
    <tbody>
        <% @absences.each do |key, value| %>
            <tr id="<%= key.barcode %>">
                <td class="barcode">
                    <%= key.barcode %>
                </td>
                <td class="value">
                    <%= value.size %>      
                </td>
                <td>
                    <ul class="nav nav-pills nav-stacked">
                        <% value.each_with_index do |v, index| %>
                            <li><%= value[index] %></li>
                        <% end %>
                    </ul>
                </td>
            </tr>
        <% end %>
    </tbody>    
</table>

<%= link_to "Back", admin_menu_path %>

app/views/entries/late_entries.html.erb
<h1> Employees arriving late</h1>
<div class="well">
    <p>Current period: <%= @current_period.description %></p>
    <p>from <%= @current_period.initial_date %> to <%= @current_period.final_date %>.</p>
    <p>Tolerance: <%= @arrival_tolerance %></p>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Barcode</th>
            <th>Late entries count</th>
            <th>Late entries dates</th>
        </tr>
    </thead>
    <tbody>
        <% @late_entries.each do |key, value| %>
            <tr>
                <td>
                    <%= key %>
                </td>
                <td>
                    <%= value.size %>      
                </td>
                <td>
                    <ul class="nav nav-pills nav-stacked">
                        <% value.each_with_index do |v, index| %>
                            <li><%= value[index].arrival_at.strftime("%F at %I:%M%p") %></li>
                        <% end %>
                    </ul>
                </td>
            </tr>
        <% end %>
    </tbody>    
</table>

<%= link_to "Back", admin_menu_path %>

app/views/entries/working_hours.html.erb
<h1>Working hours employee with badge <%= @barcode %></h1>
<div class="well">
    <p>Current period: <%= @current_period.description %></p>
    <p>From <%= @current_period.initial_date %> to <%= @current_period.final_date %>.</p>
    <p>Payday date: <%= @current_period.payday %></p>
    Days remaining to reach the payday:  <%=  @current_period.days_to_payday(@current_period.payday) %>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Date</th>
            <th>Arrival - Departure</th>
            <th>Working hours</th>
        </tr>
    </thead>
    <tbody>
        <% @employee_entries.each do |entry| %>
            <tr>
                <td>
                    <%= entry.arrival_at.strftime("%F") %>
                </td>
                <td>
                    <%= entry.arrival_at.strftime("%I:%M%p") %> - <%= entry.departure_at.strftime("%I:%M%p")  %>      
                </td>
                <td>
                    <%= calculate_hours(entry.arrival_at, entry.departure_at) %>
                </td> 
            </tr>
        <% end %>
    </tbody>    
</table>

<%= link_to "Back", employee_menu_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Punchout", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
        <li></li>
        <% if current_user %>
          <li><%= link_to "Admin menu", admin_menu_path %></li>
        <% else %>
          <li><%= link_to "Employee Working Hours Report", employee_menu_path %><li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Admin", login_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Punchout</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <%= render "layouts/header" %>

    <div class="container">
      <%= render "shared/flash_messages" %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <h2><%=raw t('errors.template.header', count: object.errors.count,
                     model: t("activerecord.models.#{object.class.name.downcase}")) %>.</h2>
        <p><%= t('errors.template.body') %></p>

        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li><%=raw msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" >
      <span> &times; </span>
    </button>
    <%= value %>
  </div>
<% end %>

app/views/welcome/admin_menu.html.erb
<h1>Admin Menu</h1>
<%= link_to "Employees arriving late", late_entries_path, class: "btn btn-primary btn-lg btn-block" %>
<div class="well">
  <h3>Be able to see which employees are arriving late.</h3>
  <h4>Assumptions:</h4>
  <ul>
    <li>This part (Employees Arriving Late) is only accessible to an registered user 
      (admin).</li>
    <li>Assuming that the entries table is already loaded with data from the 
      punchcard.</li>
    <li>The current period is calculated automatically using today date.</li>
    <li>There are not Holidays</li>
    <li>The workweek is from Monday to Friday</li>
  </ul>
</div>
<%= link_to "Employees with absences", employees_absences_path, class: "btn btn-primary btn-lg btn-block" %>
<div class="well">
  <h3>Know which employees are not coming to work at all.</h3>
  <h4>Assumptions:</h4>
  <ul>
    <li>This part (Employees Absences) is only accessible to an registered user 
      (admin).</li>
    <li>Assuming that the entries table is already loaded with data from the 
      punchcard.</li>
    <li>The current period is calculated automatically using today date.</li>
  </ul>
</div>

<p>The app uses the following data tables <%= link_to "Entity Relational Diagram", "https://github.com/alanmaciel/punchout/blob/fixing_seeds/erd.pdf" %> </p>
<div class="well">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">
        Entry table
      </h3>
    </div>
    <div class="panel-body">
      <p>
        Is populated somehow with the entries data from the punchcard machine.
      </p>
    </div>
  </div>
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">
        Period table
      </h3>
    </div>
    <div class="panel-body">
      <p>
        Is populated by the admin user, the punchout app needs the period's initial and final date, the payday, and a text description for the period.
      </p>
      <p>
        IMPORTANT: maybe you need to update in the database the payday date, as employees can review their periods entries only if today is 3 days before the payday date. 
      </p>
    </div>
    </div>
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">
          Schedule table
        </h3>
      </div>
      <div class="panel-body">
        <p>
          Is populated by the admin user too, the punchout app needs the arrival tolerance and the working time schedule (start at and ends at).
        </p>
      </div>
    </div>
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">
          User table
        </h3>
      </div>
      <div class="panel-body">
        <p>
          The user table is only for admin users, the employees doesn't need to log in to see theirs entries, they only need theirs badge barcode number.
        </p>
      </div>
    </div>
</div>

app/views/welcome/employee_menu.html.erb
<div id="barcodebox" style="margin-top:10px;" class="mainbox col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-title">Working Hours Report</div>
    </div>
    <div style="padding-top:30px" class="panel-body" >
      <%= form_tag working_hours_path do %>
        <%= label_tag "Badge Barcode" %>
        <p>
          Please type your badge card carcode and press Continue.
        </p>

        <div class="form-group form-group-md input-group">

          <div class="input-group-addon">
            <span class="glyphicon glyphicon-credit-card"></span>
          </div>
          <%= text_field_tag :barcode, nil, required: true, autofocus: true, class: "form-control" %>
        </div>
        <%= submit_tag "Continue", class: "btn btn-primary btn-md" %>
      <% end %>
    </div>
  </div>
  <p class="well">IMPORTANT: Remember that you can review your Working Hours Report <strong>ONLY 3 days before</strong> the payday date.</p>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Textile.Co.</h1>
  <h2>Welcome to punchout app</h2>
  <p>Instructions:</p>
  <ul>
    <li>
      As Textile. Co. employee you should have a BADGE card printed with a unique barcode,
      each employee has a different BADGE card.
    </li>
    <li>
      You can review your current period Working Hours Report
      (only 3 days before the paycheck day).
    </li>
    <li>
      Please click the following button to review your Working Hours Report,
      Remember to have your Badge Card at hand, you will need your barcode number:
    </li>
  </ul>
  <p><%= mail_to "alan.maciel.salcedo@gmail.com", "Help and support" %></p>
  <%= link_to "Review Your Working Hours Report", employee_menu_path,  class: "btn btn-primary btn-lg", role: "button"%>
</div>